/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Szalma Szilard
 */
import classes.Book;
import lists.Konyvlista;
import  GUI.GUI;
import javax.swing.JOptionPane;
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    //cim szerzo: jtextfield
    //jlable:cimke eleje
    // add button
    
    public AddBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddAzonBook = new javax.swing.JLabel();
        BookField = new javax.swing.JTextField();
        AddCimBook = new javax.swing.JLabel();
        BookField2 = new javax.swing.JTextField();
        AddIroBook = new javax.swing.JLabel();
        BookField3 = new javax.swing.JTextField();
        AddKiadoBook = new javax.swing.JLabel();
        BookField4 = new javax.swing.JTextField();
        AddKiadasEveBook = new javax.swing.JLabel();
        BookField5 = new javax.swing.JTextField();
        SaveBookButton = new javax.swing.JButton();
        ExitBookButton = new javax.swing.JButton();
        Hozzaferheto = new javax.swing.JLabel();
        BookField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddAzonBook.setText("Azonositó: ");

        BookField.setToolTipText("");
        BookField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFieldActionPerformed(evt);
            }
        });

        AddCimBook.setText("Cím: ");

        BookField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookField2ActionPerformed(evt);
            }
        });

        AddIroBook.setText("Író: ");

        BookField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookField3ActionPerformed(evt);
            }
        });

        AddKiadoBook.setText("Kiadó:");

        BookField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookField4ActionPerformed(evt);
            }
        });

        AddKiadasEveBook.setText("Kiadás Éve:");

        BookField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookField5ActionPerformed(evt);
            }
        });

        SaveBookButton.setBackground(new java.awt.Color(255, 0, 0));
        SaveBookButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveBookButton.setText("Save!");
        SaveBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBookButtonActionPerformed(evt);
            }
        });

        ExitBookButton.setBackground(new java.awt.Color(0, 0, 0));
        ExitBookButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitBookButton.setText("Exit");
        ExitBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBookButtonActionPerformed(evt);
            }
        });

        Hozzaferheto.setText("Hozzáférhető");
        Hozzaferheto.setToolTipText("");

        BookField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddKiadoBook, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BookField4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddIroBook, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BookField3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddCimBook, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BookField2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddAzonBook, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BookField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddKiadasEveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hozzaferheto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ExitBookButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BookField5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SaveBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(BookField6)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddAzonBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddCimBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddIroBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddKiadoBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(BookField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AddKiadasEveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(BookField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Hozzaferheto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(SaveBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExitBookButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookFieldActionPerformed

    private void BookField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookField2ActionPerformed

    private void BookField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookField3ActionPerformed

    private void BookField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookField4ActionPerformed

    private void BookField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookField5ActionPerformed

    private void SaveBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBookButtonActionPerformed
        // TODO add your handling code here:
        //adatok mentése...
        //kilépés
        //lekérdezés jtextfield get content egy egy stringbe
        //new konyv letrehozas, setteles
        //konyv to konylista(add)
        Book k = new Book();
        k.setAzonosito(BookField.getText());
        k.setCim(BookField2.getText());
        k.setIro(BookField3.getText());
        k.setKiado(BookField4.getText());
        k.setKiadas_eve(Integer.parseInt(BookField5.getText()));
        k.setHozzaferheto(Boolean.parseBoolean(BookField6.getText()));

        GUI.lista1.csatolLista(k);
        JOptionPane.showMessageDialog(this,"Book was added succesfully...");
        GUI.lista1.KiListaz();
        BookField.setText("");
        BookField2.setText("");
        BookField3.setText("");
        BookField4.setText("");
        BookField5.setText("");
        BookField6.setText("");
        
        


 
    }//GEN-LAST:event_SaveBookButtonActionPerformed

    private void ExitBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBookButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitBookButtonActionPerformed

    private void BookField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddAzonBook;
    private javax.swing.JLabel AddCimBook;
    private javax.swing.JLabel AddIroBook;
    private javax.swing.JLabel AddKiadasEveBook;
    private javax.swing.JLabel AddKiadoBook;
    private javax.swing.JTextField BookField;
    private javax.swing.JTextField BookField2;
    private javax.swing.JTextField BookField3;
    private javax.swing.JTextField BookField4;
    private javax.swing.JTextField BookField5;
    private javax.swing.JTextField BookField6;
    private javax.swing.JButton ExitBookButton;
    private javax.swing.JLabel Hozzaferheto;
    private javax.swing.JButton SaveBookButton;
    // End of variables declaration//GEN-END:variables

}

